### ISSUE TITLE
Pip install usage

### ISSUE THREAD

**Issue by sgsharma** [Polymathian/aws-codeartifact-python-proxy#2]
Thanks for making this. Could you give a few more details on how to use with `pip install`?

For example, I have this running on localhost port 5000 but trying to install a package like so: `pip install jeepney --proxy http://localhost:5000/` fails with the following:

```
Looking in indexes: https://pypi.python.org/simple/
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 405 METHOD NOT ALLOWED'))': /simple/jeepney/
```

In docker logs I see this:
```
web_1  | INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:31:47] "GET / HTTP/1.1" 200 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:31:48] "GET /favicon.ico HTTP/1.1" 200 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:31:59] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:31:59] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:32:00] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:32:01] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:32:03] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:32:07] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
web_1  | INFO:werkzeug:172.18.0.1 - - [22/Jan/2021 01:32:07] "CONNECT pypi.python.org:443 HTTP/1.0" 405 -
```

Some other potentially relevant details:
I'm running with a docker-compose file (.yml below) and using the command `docker-compose up --build` :

```
version: '3'
services:
    web:
        build: .
        ports:
            - '5000:5000'
        env_file:
            - .env
```

**Comment by gricey432** [comment]
The `--proxy` flag is for http proxies, you want to be using the `--index-url` or `-i` flag
```
pip install jeepney --index-url http://localhost:5000/
```

I can totally see how this package being named a "proxy" was probably a confusing choice though 😂

I'll take an action here to add more instructions to the readme.

**Comment by sgsharma** [comment]
Thank you! Figured out a couple days ago but forgot to update here. It works for me now (:

**Comment by sgsharma** [comment]
I've added a docker-compose and updates to the README in my fork here if you'd like to pull those in: https://github.com/sgsharma/aws-codeartifact-python-proxy

Thanks again for this!
